# Некоторый обзор Numpy

Numpy - библиотека для научных расчетов на python. Библиотека позволяет производить быстрые и эффективные вычислиния с многомерными массивами, а так же интсрументы для работы с ними.

## Arrays

Массивы в numpy - последовательность значений одного типа, индексируемые натуральными числами. Большую часть времени вы будере работать именно с этими типом данных в различных вариациях.

Инициализация массива

In [2]:
import numpy as np

a = np.array([1, 2, 3])   # Создаем одномерный массив
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Изменяем значение элемента массива
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Создаем двухмерный массив
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print(np.arange(1, 5)) #Cоздает вектор с эелементами от 1 до 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[1 2 3 4]


Ещё несколько вариантов создания массивов

In [3]:
a = np.zeros((2,2))   # Создает матрицу (2, 2) заполненую нулями
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Создает матрицу (1, 2) заполненую еденицами.
print(b)              # Prints "[[ 1.  1.]]"
# Важно понимать, что матрица (1, 2) и массив из 2 эллементов из прошлого примера - разные вещи

c = np.full((2,2), 7)  # Создает матрицу (1, 2) заполненую заданным значением
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Создает еденичную матрицу (2, 2)
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Создает еденичную матрицу (2, 2) заполненую случаными числами (0, 1)
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.30687366 0.96432012]
 [0.26057747 0.9051099 ]]


### Индексирование

Numpy предоставляет несколько способов для индексирования:
* Slicing. Похож на слайсинг в листах питона. Слайинг можно делать сразу по нескольким измерениям.
* Integer array indexing
* Boolean array indexing

In [4]:
# Slicing

# Создадим матрицу (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Используя слайсинг, созадим матрицу b из элементов матрицы а
# будем использовать 0 и 1 строку, а так же 1 и 2 столебц
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# ОБРАТИТЕ ВНИМАНИЕ НА ИЗМЕНЕНИЕ ИСХОДОЙ МАТРИЦЫ
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[2 3]
 [6 7]]
2
77


In [5]:
# Integer array indexing

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

# Пример Integer array indexing 
# В результате получится массив размерности (3,)
# Обратите внимание, что до запятой идут индексы строк, после - столбцов
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
print()

# По-другому пример можно записать так
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]

[1 4 5]


### Несколько примеров использования индексирования

In [6]:
# Создадим новый маассив, из которого будем выбирать эллементы
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Создадим массив индексов
b = np.array([0, 2, 0, 1])

# Выберем из каждой строки элемент с индексом из b (индекс столбца берется из b) 
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"
print()

# Добавим к этим элементам 10
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [7]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Найдем эллементы матрицы a, которые больше 2
                     # В результате получим матрицу b, такой же размерности, как и a

print(bool_idx)      # Prints "[[False False]
print()              #          [ True  True]
                     #          [ True  True]]"

# Воспользуемся полученным массивом для создания нового массива, ранга 1
print(a[bool_idx])  # Prints "[3 4 5 6]"

# Аналогично
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]
[3 4 5 6]


Помните, что вы можете использовать сразу несколько типов индексирования

In [8]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]
row_r2 = a[1:2, :] 
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


### Datatypes

Все элементы в массиве numpy принадлежат одному типу. В этом плане массивы ближе к C, чем к привычным вам листам питона. Numpy имеет множество встренных типов, подходящих для решения большинства задач.

In [9]:
x = np.array([1, 2])   # Автоматический выбор типа
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Автоматический выбор типа
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Принудительное выставление типа
print(x.dtype)                         # Prints "int64"

int64
float64
int64


### Array math

К массивам (матрицам) можно применять известные вам математические операции. Следут понимать, что при этом у элементов должны быть схожие размерности. Поведение в случае не совпадения размерностей хорошо описанно в документации numpy.

In [10]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
arr = np.array([1, 2])

In [11]:
# Сложение происходит поэлеметно

# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print()
print(np.add(x, y))
print('С числом')
print(x + 1)
print('C массивом другой размерности')
print(x + arr)

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]
С числом
[[2. 3.]
 [4. 5.]]
C массивом другой размерности
[[2. 4.]
 [4. 6.]]


In [12]:
# Вычитание
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [13]:
# Деление
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
# Другие функции
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


С умножением все сложней. По умолчанию, * означает поэлементное умножение. Если вы хотите получить матричное умножение, то следует воспользоваться методом dot:

In [15]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Скалярное произведение
print(v.dot(w))
print(np.dot(v, w))
print()

# Матрица на вектор
print(x.dot(v))
print(np.dot(x, v))
print()

# Матрица на матрицу
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219

[29 67]
[29 67]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Некоторые функции

К массивам можно применять набор функций. Вот некоторые из них: min, max, sum, mean

In [16]:
x = np.array([[1,2],[3,4]])
print(x)
print()

print(np.sum(x))  # сумма всех эелементов
print(np.sum(x, axis=0))  # сумма по столбцам
print(np.sum(x, axis=1))  # сумма по строкам

[[1 2]
 [3 4]]

10
[4 6]
[3 7]


In [17]:
# Функции поддерживают векторизацю
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


### Объединение массивов

Массивы можно Объединенять. Есть горизонтальное и вертикальное объединение.

In [18]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)
print()


print(np.vstack((a,b)))
print()

print(np.hstack((a,b)))

[[3. 1.]
 [0. 6.]]
[[4. 6.]
 [4. 1.]]

[[3. 1.]
 [0. 6.]
 [4. 6.]
 [4. 1.]]

[[3. 1. 4. 6.]
 [0. 6. 4. 1.]]


### Измнения размерности

Массивы можно переформировать при помощи метода, который задает новый многомерный массив. 
Следуя следующему примеру, мы переформатируем одномерный массив из десяти элементов во двумерный массив, 
состоящий из пяти строк и двух столбцов:

In [19]:
a = np.array(range(10), float)
print(a)
print()

# Превратим в матрицу
a = a.reshape((5, 2))
print(a)
print()

# Вернем обратно
print(a.flatten())

# Другой вариант
print(a.reshape((-1)))
# Превратим в марицу (9, 1)
print(a.reshape((-1, 1)))
# Превратим в марицу (1, 9)
print(a.reshape((1, -1)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [7.]
 [8.]
 [9.]]
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


# Задания
* Создайте вектор с эелементами от 10 до 49
* Создайте вектор из нулей длины 10, но его пятый елемент должен быть равен 1
* Создайте матрицу (3, 3), заполненую от 0 до 8
* Найдите все положительные числа в np.array([1,2,0,0,4,0])
* Умножте матрицу (5, 3) на (3, 2)
* Создайте матрицу (10, 10) так, чтобы на границе были 0, а внтури 1
* Создайте рандомный вектор и отсортируйте его (тут надо подумать и вспомнить, как это делалось с листом)
* Выполните a = np.random.randint(-10, 10, size=(10, 10)) и выполните нормализацию столбцов (из каждого столбца вычесть среднее этого столбца, из каждого столбца вычесть sd этого столбца)



**P.S. Все решается в 1-2 строчки. БЕЗ ЦИКЛОВ**